// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VgcCollege.Web.Data;

#nullable disable

namespace VgcCollege.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("VgcCollege.Web.Models.ApplicationUser", b =>
            {
                b.Property<string>("Id").HasColumnType("TEXT");
                b.Property<int>("AccessFailedCount").HasColumnType("INTEGER");
                b.Property<string>("ConcurrencyStamp").HasColumnType("TEXT");
                b.Property<string>("Email").HasMaxLength(256).HasColumnType("TEXT");
                b.Property<bool>("EmailConfirmed").HasColumnType("INTEGER");
                b.Property<string>("FullName").HasColumnType("TEXT").IsRequired();
                b.Property<bool>("LockoutEnabled").HasColumnType("INTEGER");
                b.Property<DateTimeOffset?>("LockoutEnd").HasColumnType("TEXT");
                b.Property<string>("NormalizedEmail").HasMaxLength(256).HasColumnType("TEXT");
                b.Property<string>("NormalizedUserName").HasMaxLength(256).HasColumnType("TEXT");
                b.Property<string>("PasswordHash").HasColumnType("TEXT");
                b.Property<string>("PhoneNumber").HasColumnType("TEXT");
                b.Property<bool>("PhoneNumberConfirmed").HasColumnType("INTEGER");
                b.Property<string>("SecurityStamp").HasColumnType("TEXT");
                b.Property<bool>("TwoFactorEnabled").HasColumnType("INTEGER");
                b.Property<string>("UserName").HasMaxLength(256).HasColumnType("TEXT");
                b.HasKey("Id");
                b.ToTable("AspNetUsers");
            });

            modelBuilder.Entity("VgcCollege.Web.Models.Branch", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("Address").IsRequired().HasMaxLength(500).HasColumnType("TEXT");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
                b.HasKey("Id");
                b.ToTable("Branches");
            });

            modelBuilder.Entity("VgcCollege.Web.Models.Course", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<int>("BranchId").HasColumnType("INTEGER");
                b.Property<DateTime>("EndDate").HasColumnType("TEXT");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
                b.Property<DateTime>("StartDate").HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("BranchId");
                b.ToTable("Courses");
            });

            modelBuilder.Entity("VgcCollege.Web.Models.StudentProfile", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("Address").HasMaxLength(500).HasColumnType("TEXT");
                b.Property<DateTime?>("DateOfBirth").HasColumnType("TEXT");
                b.Property<string>("Email").IsRequired().HasColumnType("TEXT");
                b.Property<string>("IdentityUserId").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
                b.Property<string>("Phone").HasColumnType("TEXT");
                b.Property<string>("StudentNumber").IsRequired().HasMaxLength(20).HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("IdentityUserId");
                b.HasIndex("StudentNumber").IsUnique();
                b.ToTable("StudentProfiles");
            });
#pragma warning restore 612, 618
        }
    }
}
